name: clean_arch_cli
description: A powerful CLI tool for generating Clean Architecture structure in Flutter projects. Easily create features, use cases, and entities following Clean Architecture principles.
version: 1.0.0
repository: https://github.com/AndreyDAraya/clean_arch_cli
homepage: https://github.com/AndreyDAraya/clean_arch_cli
documentation: https://github.com/AndreyDAraya/clean_arch_cli/blob/main/README.md
issue_tracker: https://github.com/AndreyDAraya/clean_arch_cli/issues

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.4.2
  mason_logger: ^0.3.1
  path: ^1.9.0
  recase: ^4.1.0
  yaml: ^3.1.2
  cli_completion: ^0.5.1
  collection: ^1.18.0
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

executables:
  fclean: clean_arch_cli

platforms:
  linux:
  macos:
  windows:

topics:
  - clean-architecture
  - cli
  - code-generation
  - flutter
